### ISSUE TITLE
Question about colorize_mask

### ISSUE THREAD

**Issue by JingyeChen** [yandex-research/ddpm-segmentation#7]
Hello, thanks for your great work and your effort on sharing this code! However, when running the code, I encountered an issue regarding the function "colorize_mask". More specifically, when I use the following code at "pixel_classifier.py", 
```python
mask = colorize_mask(pred[0], palette)
```
an error was reported

![image](https://user-images.githubusercontent.com/57484508/190839442-ae0064b6-9c0a-47f4-84d9-a704d269dd09.png)

And it works fine when I modify it to 
```python
mask = colorize_mask(pred, palette)
```

So is it a bug?

**Comment by dbaranchuk** [comment]
Hi, thanks for reporting this! 

"save_predictions" is supposed to get "preds" as NxCxHxW array, where C=1. In this case, pred[0] just squeezes the array and makes it HxW. I guess your "preds" are NxHxW and hence it fails because pred[0] is a one-dimensional vector. 

I think we can do `preds = np.squeeze(preds)` before the loop in "save_predictions" and  leave `mask = colorize_mask(pred, palette). Thus, it will work fine for both NxHxW and Nx1xHxW. Do you want to make a PR?

**Comment by JingyeChen** [comment]
A PR is made. Thanks for your reply :D

**Comment by dbaranchuk** [comment]
Great! Thank you too :)
